### ISSUE TITLE
SliceNode

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#140] opened 2024-09-01 01:06 UTC
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Slicenode

(https://billing.slicenode.xyz)

### Rule Violations

1. No TOS
2. No Privacy Policy
3. No SLA
4. Lack of basic features (no email system setup on their pterodactyl panel so you can't reset passwords, etc)
5. No Contact Details

**Comment by EternalTheGod** [comment] 2024-09-04 15:23
Duplicate of #136

**Closed as completed by EternalTheGod** 2024-09-04 15:23 UTC
Labels: duplicate
